version: '3'

services:
  server:
    build: .
    volumes:
      - ./:/app
    ports:
      - 8080:3000
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - developmentNetwork
    command: ['npm', 'start']
  database:
    image: postgres:9.6-alpine
    ports:
      - 11543:5432
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - developmentNetwork
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DATABASE: postgres

volumes:
  database-data: {}

networks:
  developmentNetwork:
    driver: bridge
